In [2]:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [10]:
'''Yes, there is a difference in the data type of variables list_ and array_list. list_ is a Python list object while array_list 
   is a NumPy array object.'''
# printing data types of both variables
print(type(list_)) 
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [11]:
# For list_
for element in list_:
    print(type(element))

# For array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:

In [12]:
"""Yes, there will be a difference in the data type of the elements present in both the variables 
list_ and array_list."""


import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_, dtype = int)

# Print data type of each element in list_
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))
    


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [13]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [14]:
# Print the shape of num_array
print(num_array.shape)

# Print the size of num_array
print(num_array.size)

(2, 3)
6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [16]:
# Creating a 3*3 matrix containing zeros only 
zeros_matrix = np.zeros((3,3))
print(zeros_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [17]:
# Creating a identity matrix of shape (5,5)
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
